server:
  port: 80 # 服务端口号

spring:
  application:
    name: gateway-service # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: aliyun20220108:8848 # Navos服务发现地址
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user_service_route # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://user-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/user/** # 断言，路径相匹配的进行路由