server:
  port: 80 # 服务端口号

spring:
  application:
    name: gateway-service # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: aliyun20220108:8848 # Navos服务发现地址
    gateway:
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/user/**
